<SubjectScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: dp(20)

        MDLabel:
            id: subject_code_label
            text: "Subject Code: "
            halign: "center"
            font_style: "H4"
        
        MDRaisedButton:
            text: "Back"
            pos_hint: {"center_x": 0.5}
            on_release: root.go_back()  # Crida la funció go_back() en SubjectScreen
